### ISSUE TITLE
Create Activities and Activity.swift crash

### ISSUE THREAD

**Issue by alanxurox** [alanxurox/TPWACTrialB#11]
@yt-zero 
if max student is not a number OR left empty-> crash

> 2020-02-19 07:11:01.347022-0500 TPWACTrialB[4462:37657] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/alanxurox/Documents/TPWACTrialB/TPWACTrialB/ViewControllerCreateActivity.swift, line 25

**Comment by twliu1** [comment]
fixed in kksk#12

**Comment by alanxurox** [comment]
@yt-zero @ttliuu Activity name crashes if: 

> 2020-02-21 14:44:45.793202-0500 TPWACTrialB[8067:203116] *** Terminating app due to uncaught exception 'InvalidPathValidation', reason: '(child:) Must be a non-empty string and not contain '.' '#' '$' '[' or ']''

UIAlertController and UIAlertAction should be helpful (See @byoon-sketch 's method):

`

        func showMailError() {

                let sendMailErrorAlert = UIAlertController(title: "Error", message: "Your device could not           send email (or you are running on the simulator)", preferredStyle: .alert)
                let dismiss = UIAlertAction(title: "OK", style: .default, handler: nil)
                sendMailErrorAlert.addAction(dismiss)
                self.present(sendMailErrorAlert, animated: true, completion: nil)
            }
`

**Comment by yt-zero** [comment]
updated error:
Terminating app due to uncaught exception 'InvalidFirebaseData', reason: '(setValue:) Cannot store object of type __NSTaggedDate at due. Can only store objects of type NSNumber, NSString, NSDictionary, and NSArray.'

**Comment by twliu1** [comment]
@yt-zero You need to write how did you get the error

try use getdatestring when trying to store date

**Comment by twliu1** [comment]
FIXED IN KKSK#14

**Comment by alanxurox** [comment]
gj tiwi

TW <notifications@github.com> 于 2020年2月24日周一 上午10:58写道：
